// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojleksibqzqzjsjlfmpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qbGVrc2licXpxempzamxmbXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMTQyOTUsImV4cCI6MjA1Njg5MDI5NX0.YEjRvFGoxVk0Eg0qSUTPQv2eAq5BQbNB588xp5254hM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);