
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojleksibqzqzjsjlfmpu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qbGVrc2licXpxempzamxmbXB1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMTQyOTUsImV4cCI6MjA1Njg5MDI5NX0.YEjRvFGoxVk0Eg0qSUTPQv2eAq5BQbNB588xp5254hM";

// For debugging only - log the connection details
console.log('Initializing Supabase client:');
console.log('URL:', SUPABASE_URL);
console.log('Key exists:', !!SUPABASE_PUBLISHABLE_KEY);

// Create the Supabase client with enhanced debugging
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});

// Function to test the Supabase connection
export const testConnection = async (): Promise<boolean> => {
  try {
    console.log('Testing Supabase connection with ping_db function...');
    const { data, error } = await supabase.rpc('ping_db');
    
    if (error) {
      console.error('Supabase ping_db test failed:', error);
      return false;
    }
    
    console.log('Supabase connection successful:', data);
    return true;
  } catch (err) {
    console.error('Exception in Supabase ping test:', err);
    return false;
  }
};

// Export a function to fetch projects that can be used directly
export const fetchProjects = async () => {
  console.log('Fetching projects from Supabase...');
  try {
    const { data, error, status } = await supabase
      .from('projects')
      .select('*')
      .order('created_at', { ascending: false });
      
    console.log('Projects fetch status:', status);
    
    if (error) {
      console.error('Error fetching projects:', error);
      throw error;
    }
    
    console.log('Projects fetched successfully, count:', data?.length || 0);
    return data || [];
  } catch (err) {
    console.error('Exception in fetchProjects:', err);
    throw err;
  }
};

// Run a direct test request to verify API connectivity
export const testDirectRequest = async (): Promise<{ success: boolean; message: string }> => {
  try {
    console.log('Testing direct API connectivity to Supabase...');
    const response = await fetch(`${SUPABASE_URL}/rest/v1/projects?select=id`, {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
        'Authorization': `Bearer ${SUPABASE_PUBLISHABLE_KEY}`,
        'Content-Type': 'application/json'
      }
    });
    
    console.log('Direct API test status:', response.status);
    
    if (!response.ok) {
      const errorText = await response.text();
      console.error('Direct API test failed:', errorText);
      return { success: false, message: `API returned status ${response.status}: ${errorText}` };
    }
    
    const data = await response.json();
    console.log('Direct API test succeeded:', data);
    return { success: true, message: 'API connection successful' };
  } catch (err: any) {
    console.error('Direct API test exception:', err);
    return { success: false, message: err.message || 'Unknown network error' };
  }
};
